### ISSUE TITLE
get_data() error handling - misleading errors if headers are incorrect

### ISSUE THREAD

**Issue by melody-shellman** [project-pareto/project-pareto#322]
Point to note here is that if the user makes an error and does not define the parameters from the second line, instead uses the first line for the header i.e. A1 as the header row and not A2 as mentioned in the PR, then the warning or the error message is way to difficult to trace. Can there be a better warning here so that we can trace the error message. 

Traceback (most recent call last):
  File "C:\Users\javal.vyas\Desktop\github\project-pareto_forked\pareto\strategic_water_management\run_strategic_model.py", line 64, in <module>
    strategic_model = create_model(
  File "c:\users\javal.vyas\desktop\github\project-pareto_forked\pareto\strategic_water_management\strategic_produced_water_optimization.py", line 1312, in create_model
    initialize={
  File "c:\users\javal.vyas\desktop\github\project-pareto_forked\pareto\strategic_water_management\strategic_produced_water_optimization.py", line 1313, in <dictcomp>
    key: pyunits.convert_value(
  File "C:\Users\javal.vyas\AppData\Local\anaconda3\envs\pareto-env\lib\site-packages\pyomo\core\base\units_container.py", line 1359, in convert_value
    raise UnitsError(
pyomo.core.base.units_container.UnitsError: The argument "num_value" in convert_value must be a native numeric type, but instead type {type(num_value)} was found.

The reason it is hard is because you would go and check the parameter tab in the input sheet and find that it is exactly how it should be and be perplexed but this units error. It would be nice to check if the data is being initialized from the second line (i.e. header is in the second line), or may be add a potential warning message that the parameter table should start from A2 and not A1.

_Originally posted by @JavalVyas2000 in https://github.com/project-pareto/project-pareto/pull/291#discussion_r1580577497_

**Comment by ksbeattie** [comment]
@ElmiraShamlou, have you had a chance to look at this?
