### ISSUE TITLE
Errors due to changes in Pyomo 6.1

### ISSUE THREAD

**Issue by lbianchi-lbl** [project-pareto/project-pareto#62]
The current version of Pyomo, 6.1.1, introduced changes to the Pyomo API that are the likely cause of errors encountered when running Pareto code. This can be seen in some of the CI jobs, e.g. https://github.com/project-pareto/project-pareto/runs/3403772682?check_suite_focus=true

```txt
Reading file from D:\a\project-pareto\project-pareto\pareto\case_studies\toy_case_study.xlsx
ERROR: Constructing component 'p' from data=None failed: KeyError: "Cannot
    treat the scalar component 'p' as an indexed component"
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\a\project-pareto\project-pareto\pareto\case_studies\toy_case_study.py", line 91, in <module>
    strategic_model = create_model(df_sets, df_parameters)
  File "D:\a\project-pareto\project-pareto\pareto\case_studies\toy_case_study.py", line 16, in create_model
    model.p = Set(initialize=df_sets['ProductionPads'],doc='Production Pads')
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\pyomo\core\base\block.py", line 541, in __setattr__
    self.add_component(name, val)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\pyomo\core\base\block.py", line 1086, in add_component
    val.construct(data)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\pyomo\core\base\disable_methods.py", line 115, in construct
    return base.construct(self, data)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\pyomo\core\base\set.py", line 1990, in construct
    IndexedComponent.__getitem__(self, index)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\pyomo\core\base\indexed_component.py", line 511, in __getitem__
    validated_index = self._validate_index(index)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\pyomo\core\base\indexed_component.py", line 730, in _validate_index
    raise KeyError(
KeyError: "Cannot treat the scalar component 'p' as an indexed component"
```

The short-term fix is to add a constraint for the Pyomo version in `setup.py` so that 6.0 rather than 6.1 is installed as a Pareto dependency.

**Comment by ksbeattie** [comment]
@Andresj89 will work on the fix for the failing test in PR #92
